// ============================================
// TEAM DATA - Edit this file to add your team!
// ============================================

export const technicalPanel = [
  {
    id: 1,
    name: "Kajal Israni",
    role: "Technical Secretary",
    imageUrl: "/src/assets/team/kajalisrani.jpeg",
    instagram: "https://www.instagram.com/kajalisrani4?igsh=aDkzMmM2YWpqcW4=",
    linkedin: "https://www.linkedin.com/in/kajalisrani?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 2,
    name: "Vaishnavi Waghole",
    role: "Assistant Technical Secretary Computer",
    imageUrl: "/src/assets/team/vaishnaviwaghole.jpeg",
    instagram: "https://www.instagram.com/vaishnavii_868?igsh=MXc1N2pmNWV3Z2dscg==",
    linkedin: "https://www.linkedin.com/in/vaishnavi-waghole-00a2a12a2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "",
  },
  {
    id: 3,
    name: "Sakshi Shinde",
    role: "Assistant Technical Secretary IT",
    imageUrl: "/src/assets/team/sakshishinde.jpeg",
    instagram: "https://www.instagram.com/_sakshi_2909?igsh=MTFzamI1NXhueTI1aw==",
    linkedin: "https://www.linkedin.com/in/sakshi-shinde-b65314370?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 4,
    name: "Prachiti Mujumdar",
    role: "Assistant Technical Secretary Instrumentation",
    imageUrl: "/src/assets/team/prachitimujumdar.jpeg",
    instagram: "https://www.instagram.com/thesorted.mess?utm_source=qr&igsh=aWlrYmZ5aHRkenhk",
    linkedin: "https://www.linkedin.com/in/prachiti-mujumdar-955160255?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 5,
    name: "Avidnya Nalawade",
    role: "Assistant Technical Secretary Mechanical",
    imageUrl: "/src/assets/team/avidnyanalawade.jpeg",
    instagram: "https://www.instagram.com/avidnya__13?igsh=MXZ1NTFkazJyNms1dg==",
    linkedin: "https://www.linkedin.com/in/avidnya-nalawade-3a280b296?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 6,
    name: "Vidhisha Thool",
    role: "Assistant Operations Secretary ENTC",
    imageUrl: "/src/assets/team/vidishathool.jpeg",
    instagram: "https://www.instagram.com/vidi_t05?igsh=MXNyOWR2eWk1OXA1aA==",
    linkedin: "https://www.linkedin.com/in/vidisha-thool-7a3132319?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 7,
    name: "Anagha Nikam",
    role: "Assistant Operations Secretary IT",
    imageUrl: "/src/assets/team/anaghanikam.jpeg",
    instagram: "https://www.instagram.com/_anaghanikam?igsh=MTF0eDg5OXpmdmd3Yw==",
    linkedin: "https://www.linkedin.com/in/anagha-nikam-355b46296?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
];

export const developmentTeam = [
  // Priority 6 - Website Leads/Co-Leads
  {
    id: 1,
    name: "Gungun Ramchandani",
    role: "Website Lead",
    imageUrl: "/src/assets/team/gungunramchandani.jpeg",
    instagram: "https://www.instagram.com/ramchandani.gungun?igsh=eTY4eHdjenV0ZjZp",
    linkedin: "https://linkedin.com/in/gungun-ramchandani-27978b259",
    github: "",
  },
  {
    id: 2,
    name: "Sameeksha Tantak",
    role: "Website Lead",
    imageUrl: "/src/assets/team/sameekshatantak.png",
    instagram: "https://www.instagram.com/sameekshatantak/",
    linkedin: "https://www.linkedin.com/in/sameeksha-tantak-186184213",
    github: "",
  },
  {
    id: 3,
    name: "Anusha Kinikar",
    role: "Website Co-Lead",
    imageUrl: "/src/assets/team/anushakinikar.jpg",
    instagram: "https://www.instagram.com/anushhaa06",
    linkedin: "https://www.linkedin.com/in/anusha-kinikar-b89600253",
    github: "",
  },
  {
    id: 4,
    name: "Sneha Mukane",
    role: "Developer",
    imageUrl: "/src/assets/team/snehamukane.jpeg",
    instagram: "https://www.instagram.com/sneha_mukane?igsh=MW81bzEzMHF1ZXYyMg==",
    linkedin: "https://www.linkedin.com/in/sneha-mukane-9132532a2",
    github: "",
  },
  {
    id: 5,
    name: "Rucha Umbrajkar",
    role: "Developer",
    imageUrl: "/src/assets/team/ruchaumbrajkar.png",
    instagram: "https://www.instagram.com/umbrajkarrucha?igsh=aTJucHRjNzl5dHZv",
    linkedin: "https://www.linkedin.com/in/rucha-umbrajkar-6b7661287",
    github: "",
  },
  {
    id: 6,
    name: "Samruddhi Dargode",
    role: "Developer",
    imageUrl: "/src/assets/team/samruddhidargode.png",
    instagram: "https://www.instagram.com/sam_mu7777/",
    linkedin: "https://www.linkedin.com/in/samruddhi-dargode-450573219/",
    github: "",
    objectPosition: "center top",
  },
  {
    id: 7,
    name: "Sanika Kavade",
    role: "Developer",
    imageUrl: "/src/assets/team/sanikakavade.jpeg",
    instagram: "https://www.instagram.com/sanika_k_15?igsh=OWFhM3h0cHNrNmpx",
    linkedin: "https://www.linkedin.com/in/sanika-kavade-089334273?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "",
  },
  {
    id: 8,
    name: "Vedika Kayangude",
    role: "Developer",
    imageUrl: "/src/assets/team/vedikakayangude.jpg",
    instagram: "https://www.instagram.com/vedika.kayangude?igsh=MXdpczRrbTFxYWhpYg==",
    linkedin: "https://www.linkedin.com/in/vedika-kayangude-760622282",
    github: "",
  },
  {
    id: 9,
    name: "Anushka Ahirrao",
    role: "Developer",
    imageUrl: "/src/assets/team/anushkaahirrao.jpg",
    instagram: "https://www.instagram.com/anushkaahirrao?igsh=ZmFyaHlpdzZ2NDQy",
    linkedin: "https://www.linkedin.com/in/anushka-ahirrao-6504a82a1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "",
  },
  {
    id: 10,
    name: "Richa Rathi",
    role: "Developer",
    imageUrl: "/src/assets/team/richarathi.jpeg",
    instagram: "https://www.instagram.com/richa.rathi.2511?igsh=MTZkcGxydG5weHd2MA==",
    linkedin: "https://www.linkedin.com/in/richa-rathi-775871257?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 11,
    name: "Shruti Bhavsar",
    role: "Developer",
    imageUrl: "/src/assets/team/shrutibhavsar.jpg",
    instagram: "https://www.instagram.com/coz.of.you.shruti?igsh=MXA0aHp1eGU3Y3Iwag==",
    linkedin: "https://www.linkedin.com/in/shruti-bhavsar-827783247?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 12,
    name: "Mayuri Dandekar",
    role: "Developer",
    imageUrl: "/src/assets/team/mayuridandekar.jpeg",
    instagram: "https://www.instagram.com/mayxuri/",
    linkedin: "https://www.linkedin.com/in/mayuri-dandekar-2a37ba299",
    github: "",
  },
  {
    id: 13,
    name: "Aditi Mahadik",
    role: "Developer",
    imageUrl: "/src/assets/team/aditimahadik.jpg",
    instagram: "https://www.instagram.com/__aditi_mahadik__/",
    linkedin: "https://www.linkedin.com/in/aditi-mahadik-226a47285/",
    github: "",
  },
  // Designers
  {
    id: 14,
    name: "Aadya Singh",
    role: "Designer",
    imageUrl: "/src/assets/team/aadyasingh.jfif",
    instagram: "https://www.instagram.com/aadyas.10/",
    linkedin: "https://www.linkedin.com/in/aadyas1065/",
    github: "",
  },
  {
    id: 15,
    name: "Radha Kulkarni",
    role: "Designer",
    imageUrl: "/src/assets/team/radhakulkarni.png",
    instagram: "https://www.instagram.com/radhask_7?igsh=YzNwejE4aHo2ZHFj",
    linkedin: "https://www.linkedin.com/in/radha-kulkarni-291127338?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "",    objectPosition: "center top",  },
  {
    id: 16,
    name: "Harshada Dhas",
    role: "Designer",
    imageUrl: "/src/assets/team/harshadadhas.jpg",
    instagram: "https://www.instagram.com/harshada_dhas?igsh=MTN3NnhsaG8zeGRxZg==",
    linkedin: "https://www.linkedin.com/in/harshadadhas?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "",
  },
  {
    id: 17,
    name: "Rutuja Khairnar",
    role: "Designer",
    imageUrl: "/src/assets/team/rutujakhairnar.jpeg",
    instagram: "https://www.instagram.com/rutuja._20/",
    linkedin: "https://www.linkedin.com/in/rutujaskhairnar/",
    github: "",
  },
  {
    id: 18,
    name: "Eshwari Borade",
    role: "Designer",
    imageUrl: "/src/assets/team/eshwariborade.jpeg",
    instagram: "https://www.instagram.com/eshwariborade",
    linkedin: "https://www.linkedin.com/in/eshwari-borade-340524292/",
    github: "",
  },
];