// ============================================
// TEAM DATA - Edit this file to add your team!
// ============================================
// Replace placeholder names, roles, image URLs, and social links with real data.
// For images, use direct URLs to photos (e.g., hosted on imgur, cloudinary, or place in public/ folder)

export const technicalPanel = [
  {
    id: 1,
    name: "Member 1",
    role: "Technical Head",
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 2,
    name: "Member 2",
    role: "Technical Co-Head",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 3,
    name: "Member 3",
    role: "ML Lead",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 4,
    name: "Member 4",
    role: "Cloud Lead",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 5,
    name: "Member 5",
    role: "Cybersecurity Lead",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 6,
    name: "Member 6",
    role: "IoT Lead",
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 7,
    name: "Member 7",
    role: "Data Science Lead",
    imageUrl: "https://images.unsplash.com/photo-1507842072343-583f20270319?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 8,
    name: "Member 8",
    role: "Blockchain Lead",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3af8abd8?auto=format&fit=crop&q=80&w=500",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
];

export const developmentTeam = [
  {
    id: 9,
    name: "Dev Member 1",
    role: "Dev Lead",
    imageUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 10,
    name: "Dev Member 2",
    role: "Frontend Developer",
    imageUrl: "https://randomuser.me/api/portraits/women/25.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 11,
    name: "Dev Member 3",
    role: "Backend Developer",
    imageUrl: "https://randomuser.me/api/portraits/men/51.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 12,
    name: "Dev Member 4",
    role: "Full Stack Developer",
    imageUrl: "https://randomuser.me/api/portraits/women/63.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 13,
    name: "Dev Member 5",
    role: "UI/UX Designer",
    imageUrl: "https://randomuser.me/api/portraits/men/36.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 14,
    name: "Dev Member 6",
    role: "Mobile Developer",
    imageUrl: "https://randomuser.me/api/portraits/women/79.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 15,
    name: "Dev Member 7",
    role: "DevOps Engineer",
    imageUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
  {
    id: 16,
    name: "Dev Member 8",
    role: "QA Engineer",
    imageUrl: "https://randomuser.me/api/portraits/women/55.jpg",
    instagram: "https://instagram.com/",
    linkedin: "https://linkedin.com/in/",
    github: "https://github.com/",
  },
];
